In [243]:
#W = np.random.random(2 , 3) * 0.0001 

W = np.array([[1,2,0], [2,-4,0.5], [3,-1,-0.5]])
X = np.array([[0.5,0.4], [0.8,0.3], [0.3,0.8], [-0.4,0.3],[-0.3,0.7],[-0.4,-0.5]])
X = np.hstack([X, np.ones((X.shape[0],1))])
W = W.T

scoress = X.dot(W)

"""scores = X[0].dot(W)
print("scores:",scores)
scores -=  np.max(scores)
print("scores restados:",scores)
print("exponencial scores", np.exp(scores))
print("suma exponencial", np.sum(np.exp(scores)))
q = np.exp(scores) / np.sum(np.exp(scores))
print("q",q)
print("log q0",-np.log(q[0]))
"""
print("---------------")

print("\nscoress Max1:",scoress, "Max", np.max(scoress, axis = 1))
print("\nscoress Max2:",scoress, "Max", np.amax(scoress, axis =1, keepdims = True))

scoressRes = np.subtract(scoress.T, np.max(scoress, axis = 1)).T
print("scores restados:",scoressRes)
scoressRes2 = np.subtract(scoress, np.amax(scoress, axis = 1, keepdims = True))
print("scores restados:",scoressRes2)

print("exponencial scores", np.exp(scoress))
print("suma exponencial", np.sum(np.exp(scoress), axis = 1))

q = (np.exp(scoress).T / np.sum(np.exp(scoress), axis = 1)).T
print("q",q)
loss = -np.log(q)
print("log loss ",loss[[0,1,2,3,4,5], [0,0,0,1,1,2]])

print("loss i",loss[[0,1,2,3,4,5], [0,0,0,1,1,2]])

print("---------------")
q[2]


---------------

scoress Max1: [[ 1.3 -0.1  0.6]
 [ 1.4  0.9  1.6]
 [ 1.9 -2.1 -0.4]
 [ 0.2 -1.5 -2. ]
 [ 1.1 -2.9 -2.1]
 [-1.4  1.7 -1.2]] Max [ 1.3  1.6  1.9  0.2  1.1  1.7]

scoress Max2: [[ 1.3 -0.1  0.6]
 [ 1.4  0.9  1.6]
 [ 1.9 -2.1 -0.4]
 [ 0.2 -1.5 -2. ]
 [ 1.1 -2.9 -2.1]
 [-1.4  1.7 -1.2]] Max [[ 1.3]
 [ 1.6]
 [ 1.9]
 [ 0.2]
 [ 1.1]
 [ 1.7]]
scores restados: [[ 0.  -1.4 -0.7]
 [-0.2 -0.7  0. ]
 [ 0.  -4.  -2.3]
 [ 0.  -1.7 -2.2]
 [ 0.  -4.  -3.2]
 [-3.1  0.  -2.9]]
scores restados: [[ 0.  -1.4 -0.7]
 [-0.2 -0.7  0. ]
 [ 0.  -4.  -2.3]
 [ 0.  -1.7 -2.2]
 [ 0.  -4.  -3.2]
 [-3.1  0.  -2.9]]
exponencial scores [[ 3.66929667  0.90483742  1.8221188 ]
 [ 4.05519997  2.45960311  4.95303242]
 [ 6.68589444  0.12245643  0.67032005]
 [ 1.22140276  0.22313016  0.13533528]
 [ 3.00416602  0.05502322  0.12245643]
 [ 0.24659696  5.47394739  0.30119421]]
suma exponencial [  6.39625289  11.4678355    7.47867092   1.5798682    3.18164567
   6.02173857]
q [[ 0.57366348  0.14146367  0.28487285]
 [

In [281]:
X = np.array([[1,2,3],
     [3,2,1],
     [7,5,6],
     [0,2,3]])

q = [[1,2],
     [0,1],
     [8,3],
     [2,2]]

dW = np.zeros((3,4))
"""for i on images
    for j on classes
        #dW[,j] += (q[i,j] - (j == y[i])) * X[i]
        dW[,j] += (q[i,j] - (j == y[i])) * X[i]
"""

#dW[:,1] += X[2] * 2
print(X.T)
print(dW + X.T)



[[1 3 7 0]
 [2 2 5 2]
 [3 1 6 3]]
[[ 1.  3.  7.  0.]
 [ 2.  2.  5.  2.]
 [ 3.  1.  6.  3.]]


In [286]:
np.random.seed(1)
X = 10 * np.random.randn(20, 10)
y = np.array([0, 1, 2, 2, 1])
X.shape, y.shape

((20, 10), (5,))

In [291]:
dscores = [[1,2],
        [3,4]
]
np.sum(dscores, axis = 0)

array([4, 6])

In [178]:
arr1 = np.array([[1,2],[2,2],[3,3]])
print(arr1)
print((arr1.T / [3,2,1]).T)
print(arr1 / [2,3])
print(arr1 / 3)

[[1 2]
 [2 2]
 [3 3]]
[[ 0.33333333  0.66666667]
 [ 1.          1.        ]
 [ 3.          3.        ]]
[[ 0.5         0.66666667]
 [ 1.          0.66666667]
 [ 1.5         1.        ]]
[[ 0.33333333  0.66666667]
 [ 0.66666667  0.66666667]
 [ 1.          1.        ]]


-------------------
## Net

In [356]:
hidden_size = 4
output_size = 3

X = np.array([[1,2],
              [1,-1],
              [2,0],
              [2,1],
              [2,3]])

y = np.array([1,2,0,0,1])
X.shape, y. shape

W1 = 1e-4 * np.random.randn(2, hidden_size)
b1 = np.zeros(hidden_size)
W2 = 1e-4 * np.random.randn(hidden_size, output_size)
b2 = np.zeros(output_size)


["X", X.shape, "y",y.shape, "W1",W1.shape, "W2",W2.shape]

['X', (5, 2), 'y', (5,), 'W1', (2, 4), 'W2', (4, 3)]

In [357]:
X, "W1", W1, "b1", b1, "W2", W2, "b2", b2

(array([[ 1,  2],
        [ 1, -1],
        [ 2,  0],
        [ 2,  1],
        [ 2,  3]]),
 'W1',
 array([[  9.66539250e-05,   7.13049050e-05,   1.30620607e-04,
          -6.04602969e-05],
        [  6.36583409e-05,   1.40925339e-04,   1.62091229e-04,
          -8.06184817e-05]]),
 'b1',
 array([ 0.,  0.,  0.,  0.]),
 'W2',
 array([[ -2.51674208e-05,   3.82715174e-05,  -2.88997343e-05],
        [ -3.91816240e-05,   6.84001328e-05,  -3.53409983e-05],
        [ -1.78791289e-04,   3.61847316e-05,  -4.24492791e-05],
        [ -7.31530982e-05,  -1.56573815e-04,   1.01382247e-04]]),
 'b2',
 array([ 0.,  0.,  0.]))

-------
### Fordward

In [407]:
z1 = X.dot(W1) + b1
print("z1", z1)
a1 = np.maximum(0, z1) # funcion de activacion
print("a1", a1)
scores = a1.dot(W2) + b2
print("Scores\n------\n", scores)

Fordward
------
z1 [[  2.23970607e-04   3.53155583e-04   4.54803064e-04  -2.21697260e-04]
 [  3.29955841e-05  -6.96204339e-05  -3.14706220e-05   2.01581848e-05]
 [  1.93307850e-04   1.42609810e-04   2.61241213e-04  -1.20920594e-04]
 [  2.56966191e-04   2.83535149e-04   4.23332442e-04  -2.01539076e-04]
 [  3.84282873e-04   5.65385827e-04   7.47514899e-04  -3.62776039e-04]]
a1 [[  2.23970607e-04   3.53155583e-04   4.54803064e-04   0.00000000e+00]
 [  3.29955841e-05   0.00000000e+00   0.00000000e+00   2.01581848e-05]
 [  1.93307850e-04   1.42609810e-04   2.61241213e-04   0.00000000e+00]
 [  2.56966191e-04   2.83535149e-04   4.23332442e-04   0.00000000e+00]
 [  3.84282873e-04   5.65385827e-04   7.47514899e-04   0.00000000e+00]]
Scores
------
 [[ -1.00788798e-07   4.91845105e-08  -3.82596240e-08]
 [ -2.30504742e-09  -1.89345283e-09   1.09011845e-09]
 [ -5.71603972e-08   2.66056579e-08  -2.17160197e-08]
 [ -9.32646968e-08   4.45464987e-08  -3.54168268e-08]
 [ -1.65473296e-07   8.04281803e-08

-------
### Loss

In [404]:
exp_scores = np.exp(scores)
print("exp scores", exp_scores)

suma = np.sum(exp_scores, axis=1, keepdims=True)
print("suma", suma)
probs = exp_scores / suma 
print("probs", probs)
probs_select = probs[range(X.shape[0]), y]
#probs_select = [1,1,1,1,1]
print("probs_select", probs_select)
corect_logprobs = -np.log(probs_select)
print("corect_logprobs", corect_logprobs)

data_loss = np.sum(corect_logprobs) / X.shape[0]
print("data_loss", data_loss)

print("W1*W1", W1 * W1)
print("W2*W2", W2 * W2)

reg = 0.1
reg_loss = 0.5 * reg * np.sum(W1 * W1) + 0.5 * reg * np.sum(W2 * W2)
print("reg_loss", reg_loss)
#loss = data_loss + reg_loss


exp scores [[ 0.9999999   1.00000005  0.99999996]
 [ 1.          1.          1.        ]
 [ 0.99999994  1.00000003  0.99999998]
 [ 0.99999991  1.00000004  0.99999996]
 [ 0.99999983  1.00000008  0.99999994]]
suma [[ 2.99999991]
 [ 3.        ]
 [ 2.99999995]
 [ 2.99999992]
 [ 2.99999985]]
probs [[ 0.33333331  0.33333336  0.33333333]
 [ 0.33333333  0.33333333  0.33333333]
 [ 0.33333332  0.33333335  0.33333333]
 [ 0.33333331  0.33333336  0.33333333]
 [ 0.33333329  0.33333338  0.33333333]]
probs_select [ 0.33333336  0.33333333  0.33333332  0.33333331  0.33333338]
corect_logprobs [ 1.09861221  1.09861229  1.09861233  1.09861235  1.09861216]
data_loss 1.09861226746
W1*W1 [[  9.34198122e-09   5.08438948e-09   1.70617428e-08   3.65544750e-09]
 [  4.05238437e-09   1.98599512e-08   2.62735664e-08   6.49933960e-09]]
W2*W2 [[  6.33399068e-10   1.46470904e-09   8.35194643e-10]
 [  1.53519966e-09   4.67857817e-09   1.24898616e-09]
 [  3.19663251e-08   1.30933480e-09   1.80194129e-09]
 [  5.35137577e-

-------
### Gradiente

In [410]:
print("dscores", dscores)
dscores = probs
dscores[range(X.shape[0]),y] -= 1
dscores /= X.shape[0]
print("dscores", dscores)

# W2 and b2
W2 = np.dot(a1.T, dscores)
#print(a1.shape)
b2 = np.sum(dscores, axis=0)
# next backprop into hidden layer
dhidden = np.dot(dscores, W2.T)
# backprop the ReLU non-linearity
dhidden[a1 <= 0] = 0
# finally into W,b
W1 = np.dot(X.T, dhidden)
b1 = np.sum(dhidden, axis=0)

# add regularization gradient contribution
W2 += reg * W2
W1 += reg * W1

dscores [[ 0.06666666 -0.13333333  0.06666667]
 [ 0.06666667  0.06666667 -0.13333333]
 [-0.13333334  0.06666667  0.06666667]
 [-0.13333334  0.06666667  0.06666667]
 [ 0.06666666 -0.13333332  0.06666667]]
dscores [[ 0.01333333 -0.22666667  0.01333333]
 [ 0.01333333  0.01333333 -0.22666667]
 [-0.22666667  0.01333333  0.01333333]
 [-0.22666667  0.01333333  0.01333333]
 [ 0.01333333 -0.22666666  0.01333333]]


In [406]:
arr = np.array([[1,2], [3,4]])
arr*arr

array([[ 1,  4],
       [ 9, 16]])

In [413]:
for i in range(10):
    # Compute vector of scores
    f_i = X[i].dot(W)

    # Normalization trick to avoid numerical instability, per http://cs231n.github.io/linear-classify/#softmax
    #f_i -= np.max(f_i)

    # Compute loss (and add to it, divided later)
    sum_j = np.sum(np.exp(f_i))
    p = lambda k: np.exp(f_i[k]) / sum_j
    loss += -np.log(p(y[i]))


IndexError: index 5 is out of bounds for axis 0 with size 5